election_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: your-gcp-project-id  # Replace with your GCP project ID
      dataset: philippines_election_2025_dbt
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: ../gcp-credentials/service-account-key.json  # Path to your service account key
      
    prod:
      type: bigquery
      method: service-account
      project: your-gcp-project-id  # Replace with your GCP project ID
      dataset: philippines_election_2025_prod
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
      keyfile: ../gcp-credentials/service-account-key.json
